version: '2.1'
networks:
  monitoring:
    driver: bridge
volumes:
    prometheus_data:
    grafana_data:
services:
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - 9091:9090
    expose:
      - 9091
    networks:
      - monitoring
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
    ports:
      - 8085:3000
    expose:
      - 8085
    networks:
      - monitoring
  monitoring-app:
    build:
      context: monitoring-app
    ports:
      - 9090:9090
    expose:
      - 9090
    networks:
      - monitoring
