{
 "title": "Discord activity",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Discord_name", "label": "name", "query": { "query": "label_values(name)" } }
  ]
 },
 "panels": [
  {
   "title": "Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "activity{status=\"online\"}==1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Idle",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "activity{status=\"idle\"}==1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "DND",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "activity{status=\"dnd\"}==1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(activity{})", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "User statuses",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(status) (activity{status=\"online\"}==1)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum by(status) (activity{status=\"idle\"}==1)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum by(status) (activity{status=\"dnd\"}==1)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum by(status) (activity{status=\"offline\"}==1)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Subject \"$Discord_name\" activity ",
   "type": "graph",
   "gridPos": { "h": 3, "w": 15, "x": 9, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "activity{name=\"$Discord_name\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Subject \"$Discord_name\" app activity ",
   "type": "graph",
   "gridPos": { "h": 3, "w": 15, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "game_activity{name=\"$Discord_name\"}",
     "legendFormat": "{{activity}}"
    }
   ]
  },
  {
   "title": "Offline",
   "type": "stat",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "activity{status=\"offline\"}==1",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}